name: "Compliance"

on:
  push:
    branches: [ "main" ]

# on:
#   pull_request_target:
#     types:
#       - opened
#       - edited
#       - synchronize

permissions:
  actions: write
  #pull-requests: write

jobs:
  compliance:
    uses: SyedsImran/VulnerabilityCheck/.github/workflows/blank.yml@main



# name: Workflowtest-Check
# on:
#   push:
#     branches: [ "main" ]
#   workflow_call:
# permissions:
#   pull-requests: write
  
  
