name: "Compliance"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  compliance:
    uses: open-sauced/open-sauced/.github/workflows/compliance.yml@main



# name: Workflowtest-Check
# on:
#   push:
#     branches: [ "main" ]
#   workflow_call:
# permissions:
#   pull-requests: write
  
  
